### ISSUE TITLE
mason cannot install  pyright 

### ISSUE THREAD

**Issue by Thesoul20** [chaozwn/astronvim_with_coc_or_mason#11]
能够直接使用npm 全局安装pyright ， 但是到 neovim 里就会一直出现错误。

```
 Failed
    ✗ pyright
      ▼ Displaying full log
        Wrote to /home/choose/.local/share/nvim/mason/staging/pyright/package.json:
        
        {
          "name": "@mason/pyright",
          "version": "1.0.0",
          "description": "",
          "main": "index.js",
          "scripts": {
            "test": "echo \"Error: no test specified\" && exit 1"
          },
          "keywords": [],
          "author": "",
          "license": "ISC"
        }
        
        
        Initialized npm root.
        Installing npm package pyright@1.1.322…
        npm ERR! code ETARGET
        npm ERR! notarget No matching version found for pyright@1.1.322.
        npm ERR! notarget In most cases you or one of your dependencies are requesting
        npm ERR! notarget a package version that doesn't exist.
        
        npm ERR! A complete log of this run can be found in: /home/choose/.npm/_logs/2023-08-16T02_12_54_758Z-debug-0.log
        spawn: npm failed with exit code 1 and signal 0. 
```
logs:
```
0 verbose cli /home/choose/.nvm/versions/node/v20.5.1/bin/node /home/choose/.nvm/versions/node/v20.5.1/bin/npm
1 info using npm@9.8.0
2 info using node@v20.5.1
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/home/choose/.nvm/versions/node/v20.5.1/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 1ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/home/choose/.local/share/nvim/mason/staging/pyright/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/home/choose/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/home/choose/.nvm/versions/node/v20.5.1/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:setEnvs Completed in 0ms
16 timing config:load Completed in 5ms
17 timing npm:load:configload Completed in 5ms
18 timing config:load:flatten Completed in 1ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm install pyright@1.1.322
22 verbose argv "install" "pyright@1.1.322"
23 timing npm:load:setTitle Completed in 0ms
24 timing npm:load:display Completed in 0ms
25 verbose logfile logs-max:10 dir:/home/choose/.npm/_logs/2023-08-16T02_16_07_065Z-
26 verbose logfile /home/choose/.npm/_logs/2023-08-16T02_16_07_065Z-debug-0.log
27 timing npm:load:logFile Completed in 4ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 14ms
31 timing arborist:ctor Completed in 0ms
32 silly logfile start cleaning logs, removing 2 files
33 timing arborist:ctor Completed in 0ms
34 silly logfile done cleaning log files
35 timing idealTree:init Completed in 6ms
36 timing idealTree:userRequests Completed in 1ms
37 silly idealTree buildDeps
38 silly fetch manifest pyright@1.1.322
39 http fetch GET 200 https://registry.npmmirror.com/pyright 157ms (cache hit)
40 silly placeDep ROOT pyright@ OK for: @mason/pyright@1.0.0 want: 1.1.322
41 timing idealTree:#root Completed in 160ms
42 timing idealTree:node_modules/pyright Completed in 0ms
43 timing idealTree:buildDeps Completed in 161ms
44 timing idealTree:fixDepFlags Completed in 0ms
45 timing idealTree Completed in 168ms
46 timing command:install Completed in 171ms
47 verbose type version
48 verbose stack pyright: No matching version found for pyright@1.1.322.
48 verbose stack     at module.exports (/home/choose/.nvm/versions/node/v20.5.1/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
48 verbose stack     at RegistryFetcher.manifest (/home/choose/.nvm/versions/node/v20.5.1/lib/node_modules/npm/node_modules/pacote/lib/registry.js:119:22)
48 verbose stack     at async #nodeFromEdge (/home/choose/.nvm/versions/node/v20.5.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1049:19)
48 verbose stack     at async #buildDepStep (/home/choose/.nvm/versions/node/v20.5.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:917:11)
48 verbose stack     at async Arborist.buildIdealTree (/home/choose/.nvm/versions/node/v20.5.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:196:7)
48 verbose stack     at async Promise.all (index 1)
48 verbose stack     at async Arborist.reify (/home/choose/.nvm/versions/node/v20.5.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
48 verbose stack     at async Install.exec (/home/choose/.nvm/versions/node/v20.5.1/lib/node_modules/npm/lib/commands/install.js:149:5)
48 verbose stack     at async module.exports (/home/choose/.nvm/versions/node/v20.5.1/lib/node_modules/npm/lib/cli-entry.js:61:5)
49 verbose cwd /home/choose/.local/share/nvim/mason/staging/pyright
50 verbose Linux 5.19.0-46-generic
51 verbose node v20.5.1
52 verbose npm  v9.8.0
53 error code ETARGET
54 error notarget No matching version found for pyright@1.1.322.
55 error notarget In most cases you or one of your dependencies are requesting
55 error notarget a package version that doesn't exist.
56 verbose exit 1
57 timing npm Completed in 241ms
58 verbose unfinished npm timer reify 1692152167134
59 verbose unfinished npm timer reify:loadTrees 1692152167136
60 verbose code 1
61 error A complete log of this run can be found in: /home/choose/.npm/_logs/2023-08-16T02_16_07_065Z-debug-0.log
```

**Comment by chaozwn** [comment]
> 能够直接使用npm 全局安装pyright ， 但是到 neovim 里就会一直出现错误。
> 
> ```
>  Failed
>     ✗ pyright
>       ▼ Displaying full log
>         Wrote to /home/choose/.local/share/nvim/mason/staging/pyright/package.json:
>         
>         {
>           "name": "@mason/pyright",
>           "version": "1.0.0",
>           "description": "",
>           "main": "index.js",
>           "scripts": {
>             "test": "echo \"Error: no test specified\" && exit 1"
>           },
>           "keywords": [],
>           "author": "",
>           "license": "ISC"
>         }
>         
>         
>         Initialized npm root.
>         Installing npm package pyright@1.1.322…
>         npm ERR! code ETARGET
>         npm ERR! notarget No matching version found for pyright@1.1.322.
>         npm ERR! notarget In most cases you or one of your dependencies are requesting
>         npm ERR! notarget a package version that doesn't exist.
>         
>         npm ERR! A complete log of this run can be found in: /home/choose/.npm/_logs/2023-08-16T02_12_54_758Z-debug-0.log
>         spawn: npm failed with exit code 1 and signal 0. 
> ```
> 
> logs:
> 
> ```
> 0 verbose cli /home/choose/.nvm/versions/node/v20.5.1/bin/node /home/choose/.nvm/versions/node/v20.5.1/bin/npm
> 1 info using npm@9.8.0
> 2 info using node@v20.5.1
> 3 timing npm:load:whichnode Completed in 0ms
> 4 timing config:load:defaults Completed in 1ms
> 5 timing config:load:file:/home/choose/.nvm/versions/node/v20.5.1/lib/node_modules/npm/npmrc Completed in 1ms
> 6 timing config:load:builtin Completed in 1ms
> 7 timing config:load:cli Completed in 1ms
> 8 timing config:load:env Completed in 0ms
> 9 timing config:load:file:/home/choose/.local/share/nvim/mason/staging/pyright/.npmrc Completed in 0ms
> 10 timing config:load:project Completed in 1ms
> 11 timing config:load:file:/home/choose/.npmrc Completed in 0ms
> 12 timing config:load:user Completed in 0ms
> 13 timing config:load:file:/home/choose/.nvm/versions/node/v20.5.1/etc/npmrc Completed in 0ms
> 14 timing config:load:global Completed in 1ms
> 15 timing config:load:setEnvs Completed in 0ms
> 16 timing config:load Completed in 5ms
> 17 timing npm:load:configload Completed in 5ms
> 18 timing config:load:flatten Completed in 1ms
> 19 timing npm:load:mkdirpcache Completed in 0ms
> 20 timing npm:load:mkdirplogs Completed in 0ms
> 21 verbose title npm install pyright@1.1.322
> 22 verbose argv "install" "pyright@1.1.322"
> 23 timing npm:load:setTitle Completed in 0ms
> 24 timing npm:load:display Completed in 0ms
> 25 verbose logfile logs-max:10 dir:/home/choose/.npm/_logs/2023-08-16T02_16_07_065Z-
> 26 verbose logfile /home/choose/.npm/_logs/2023-08-16T02_16_07_065Z-debug-0.log
> 27 timing npm:load:logFile Completed in 4ms
> 28 timing npm:load:timers Completed in 0ms
> 29 timing npm:load:configScope Completed in 0ms
> 30 timing npm:load Completed in 14ms
> 31 timing arborist:ctor Completed in 0ms
> 32 silly logfile start cleaning logs, removing 2 files
> 33 timing arborist:ctor Completed in 0ms
> 34 silly logfile done cleaning log files
> 35 timing idealTree:init Completed in 6ms
> 36 timing idealTree:userRequests Completed in 1ms
> 37 silly idealTree buildDeps
> 38 silly fetch manifest pyright@1.1.322
> 39 http fetch GET 200 https://registry.npmmirror.com/pyright 157ms (cache hit)
> 40 silly placeDep ROOT pyright@ OK for: @mason/pyright@1.0.0 want: 1.1.322
> 41 timing idealTree:#root Completed in 160ms
> 42 timing idealTree:node_modules/pyright Completed in 0ms
> 43 timing idealTree:buildDeps Completed in 161ms
> 44 timing idealTree:fixDepFlags Completed in 0ms
> 45 timing idealTree Completed in 168ms
> 46 timing command:install Completed in 171ms
> 47 verbose type version
> 48 verbose stack pyright: No matching version found for pyright@1.1.322.
> 48 verbose stack     at module.exports (/home/choose/.nvm/versions/node/v20.5.1/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
> 48 verbose stack     at RegistryFetcher.manifest (/home/choose/.nvm/versions/node/v20.5.1/lib/node_modules/npm/node_modules/pacote/lib/registry.js:119:22)
> 48 verbose stack     at async #nodeFromEdge (/home/choose/.nvm/versions/node/v20.5.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1049:19)
> 48 verbose stack     at async #buildDepStep (/home/choose/.nvm/versions/node/v20.5.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:917:11)
> 48 verbose stack     at async Arborist.buildIdealTree (/home/choose/.nvm/versions/node/v20.5.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:196:7)
> 48 verbose stack     at async Promise.all (index 1)
> 48 verbose stack     at async Arborist.reify (/home/choose/.nvm/versions/node/v20.5.1/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
> 48 verbose stack     at async Install.exec (/home/choose/.nvm/versions/node/v20.5.1/lib/node_modules/npm/lib/commands/install.js:149:5)
> 48 verbose stack     at async module.exports (/home/choose/.nvm/versions/node/v20.5.1/lib/node_modules/npm/lib/cli-entry.js:61:5)
> 49 verbose cwd /home/choose/.local/share/nvim/mason/staging/pyright
> 50 verbose Linux 5.19.0-46-generic
> 51 verbose node v20.5.1
> 52 verbose npm  v9.8.0
> 53 error code ETARGET
> 54 error notarget No matching version found for pyright@1.1.322.
> 55 error notarget In most cases you or one of your dependencies are requesting
> 55 error notarget a package version that doesn't exist.
> 56 verbose exit 1
> 57 timing npm Completed in 241ms
> 58 verbose unfinished npm timer reify 1692152167134
> 59 verbose unfinished npm timer reify:loadTrees 1692152167136
> 60 verbose code 1
> 61 error A complete log of this run can be found in: /home/choose/.npm/_logs/2023-08-16T02_16_07_065Z-debug-0.log
> ```

 应该是你配置了淘宝源，版本没有同步到淘宝源

**Comment by Thesoul20** [comment]
ok.
我换了一下npm 的版本之后就可以正常安装了。
