### ISSUE TITLE
wsl-open问题

### ISSUE THREAD

**Issue by NichloasChiu** [chaozwn/astronvim_with_coc_or_mason#16]
请问大佬，我是用的wsl。neo-tree操作O（使用系统打开文件），会自动判定为linux，如何让他成功判断为windows系统打开文件

**Comment by chaozwn** [comment]
> 请问大佬，我是用的wsl。neo-tree操作O（使用系统打开文件），会自动判定为linux，如何让他成功判断为windows系统打开文件

这个没办法，因为是调用的vim.cmd()所以就是调用的系统打开方式

**Comment by chaozwn** [comment]
> > 请问大佬，我是用的wsl。neo-tree操作O（使用系统打开文件），会自动判定为linux，如何让他成功判断为windows系统打开文件
> 
> 这个没办法，因为是调用的vim.cmd()所以就是调用的系统默认的打开方式。

**Comment by chaozwn** [comment]
> 请问大佬，我是用的wsl。neo-tree操作O（使用系统打开文件），会自动判定为linux，如何让他成功判断为windows系统打开文件

<img width="896" alt="image" src="https://github.com/chaozwn/astronvim_with_coc_or_mason/assets/51357674/6c29b5ac-e401-4d33-b7b3-3df8d8d724f6">

**Comment by NichloasChiu** [comment]
非常感谢，麻烦了
