### ISSUE TITLE
如何使用command line 的自动补全（迁移到V4后tab不起作用了）

### ISSUE THREAD

**Issue by xllowl** [chaozwn/astronvim_with_coc_or_mason#18]
如题
![CleanShot 2024-04-05 at 15 51 01@2x|300](https://github.com/chaozwn/astronvim_with_coc_or_mason/assets/95349351/a4f31f28-c730-4a16-b6a7-3852a3eda76b)

**Comment by chaozwn** [comment]
> 如题 ![CleanShot 2024-04-05 at 15 51 01@2x|300](https://private-user-images.githubusercontent.com/95349351/319905182-a4f31f28-c730-4a16-b6a7-3852a3eda76b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzNzQ2MzcsIm5iZiI6MTcxMjM3NDMzNywicGF0aCI6Ii85NTM0OTM1MS8zMTk5MDUxODItYTRmMzFmMjgtYzczMC00YTE2LWI2YTctMzg1MmEzZWRhNzZiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA2VDAzMzIxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjM2Y1ZGUwYmE3ODk2Mjk3MTVkZDY2NTI4NzAyMDBiNjA1MGNjZTdiNDc0OTQwMjRlODJhMWRlNWQ4ZWRjMjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yTuLGHfFsEvoWo-Mt0-3-FOaGdLGy0jj1prZBTAurQI)

fixed, use `Tab` to auto complete.
