### ISSUE TITLE
Alpha.nvim doesn't show when startup

### ISSUE THREAD

**Issue by namespacebilibili** [chaozwn/astronvim_with_coc_or_mason#2]

**Comment by chaozwn** [comment]
because i install `resession.nvim` which can restore tabs last session opened. so it should disabled alpha.vim autostart. you can open `alpha.nvim` through `<leader>h`.

**Comment by chaozwn** [comment]
you can run `nvim` after close nvim. You will find that the previous buffers have been restored to their original state.

**Comment by namespacebilibili** [comment]
> because i install `resession.nvim` which can restore tabs last session opened. so it should disabled alpha.vim autostart. you can open `alpha.nvim` through `<leader>h`.

Oh, nice of you
