### ISSUE TITLE
Error when load nvim barbecue in function 'get_file_icon'

### ISSUE THREAD

**Issue by Thesoul20** [chaozwn/astronvim_with_coc_or_mason#21]
When I open nvim at any folder, there is a error appear:
```lua
Error executing vim.schedule lua callback: ...e/.local/share/nvim/lazy/barbecue/lua/barbecue/theme.lua:172: table index is nil
stack traceback:
        ...e/.local/share/nvim/lazy/barbecue/lua/barbecue/theme.lua:172: in function 'get_file_icon'
        .../share/nvim/lazy/barbecue/lua/barbecue/ui/components.lua:82: in function 'basename'
        ...oose/.local/share/nvim/lazy/barbecue/lua/barbecue/ui.lua:106: in function 'create_entries'
        ...oose/.local/share/nvim/lazy/barbecue/lua/barbecue/ui.lua:219: in function <...oose/.local/share/nvim/lazy/barbecue/lua/barbecue/ui.lua:203>
```
the `theme.lua` file at the folder of `~/.local/share/nvim/lazy/barbecue/lua/barbecue/`.

In the `theme.lua` at line 168, the code are below:
```lua
  if file_icons[icon.name] == nil then
    file_icons[icon.name] = {
      highlight = highlight,
      color = icon.color,
    }
```

How to Fix this error.

**Comment by chaozwn** [comment]
it's barbecue code problem, any time you open a file he doesn't support, you get an error.
if you don't want to use it, maybe you can disabled it or switch to dropbar.nvim.
run `:set filetype?` then you will get a filetype. and add it in exclude_filetypes.
```lua
return {
  "utilyre/barbecue.nvim",
  name = "barbecue",
  version = "*",
  dependencies = {
    "SmiteshP/nvim-navic",
    "nvim-tree/nvim-web-devicons", -- optional dependency
  },
  opts = {
    show_modified = true,
    exclude_filetypes = { "netrw", "toggleterm", "gomod", "gosum" },
  },
}
```

**Comment by chaozwn** [comment]
I saw a guy come up with a nice commit, you update my code and then update the plugin, it should all be fixed.

**Comment by Thesoul20** [comment]
Thank you for quickly response.
In the file of `nvim/lua/plugins/barbecue.lua` I have change this file's context :
```lua
return {
  "utilyre/barbecue.nvim",
  name = "barbecue",
  version = "*",
  dependencies = {
    "SmiteshP/nvim-navic",
    "nvim-tree/nvim-web-devicons", -- optional dependency
  },
  opts = {
    show_modified = true,
    exclude_filetypes = { "netrw", "toggleterm", "gomod", "gosum" },
  },
}
```
And then I press <leader>pU to update all I used plugins.

![image](https://github.com/chaozwn/astronvim_with_coc_or_mason/assets/49742133/4cb8e5cd-522e-4b8f-9174-3f1553746cd3)


Then I exit my terminal iTerm2, and reopen it. After that, run the command  `nvim .` to enter neovim again:
```lua
Error executing vim.schedule lua callback: ...e/.local/share/nvim/lazy/barbecue/lua/barbecue/theme.lua:172: table index is nil
stack traceback:
        ...e/.local/share/nvim/lazy/barbecue/lua/barbecue/theme.lua:172: in function 'get_file_icon'
        .../share/nvim/lazy/barbecue/lua/barbecue/ui/components.lua:82: in function 'basename'
        ...oose/.local/share/nvim/lazy/barbecue/lua/barbecue/ui.lua:106: in function 'create_entries'
        ...oose/.local/share/nvim/lazy/barbecue/lua/barbecue/ui.lua:219: in function <...oose/.local/share/nvim/lazy/barbecue/lua/barbecue/ui.lua:203>
```

**Comment by chaozwn** [comment]
> Thank you for quickly response. In the file of `nvim/lua/plugins/barbecue.lua` I have change this file's context :
> 
> ```lua
> return {
>   "utilyre/barbecue.nvim",
>   name = "barbecue",
>   version = "*",
>   dependencies = {
>     "SmiteshP/nvim-navic",
>     "nvim-tree/nvim-web-devicons", -- optional dependency
>   },
>   opts = {
>     show_modified = true,
>     exclude_filetypes = { "netrw", "toggleterm", "gomod", "gosum" },
>   },
> }
> ```
> 
> And then I press pU to update all I used plugins.
> 
> ![image](https://private-user-images.githubusercontent.com/49742133/345694752-4cb8e5cd-522e-4b8f-9174-3f1553746cd3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNzA1NTgsIm5iZiI6MTcyMDA3MDI1OCwicGF0aCI6Ii80OTc0MjEzMy8zNDU2OTQ3NTItNGNiOGU1Y2QtNTIyZS00YjhmLTkxNzQtM2YxNTUzNzQ2Y2QzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA1MTczOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzYWFlZWMxM2NjZmFmNTJkZjgzMzUwMWM0NDM2Yjc0MjE3Y2E5N2RiOTllMTA0M2NkMmViMDk1MjA3M2VlMmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.zJu3WEhQ2Yqu0wTU5DLLOXn42GQ9ermrZpxrjEQMhJg)
> 
> Then I exit my terminal iTerm2, and reopen it. After that, run the command `nvim .` to enter neovim again:
> 
> ```lua
> Error executing vim.schedule lua callback: ...e/.local/share/nvim/lazy/barbecue/lua/barbecue/theme.lua:172: table index is nil
> stack traceback:
>         ...e/.local/share/nvim/lazy/barbecue/lua/barbecue/theme.lua:172: in function 'get_file_icon'
>         .../share/nvim/lazy/barbecue/lua/barbecue/ui/components.lua:82: in function 'basename'
>         ...oose/.local/share/nvim/lazy/barbecue/lua/barbecue/ui.lua:106: in function 'create_entries'
>         ...oose/.local/share/nvim/lazy/barbecue/lua/barbecue/ui.lua:219: in function <...oose/.local/share/nvim/lazy/barbecue/lua/barbecue/ui.lua:203>
> ```

it's not latest version. check update again.

**Comment by Thesoul20** [comment]
After update the barbecue plugin, the problem still appear.
Now, after enter neovim then press Space + p + s to check the versions of barbecue plugin, there are:
![image](https://github.com/user-attachments/assets/8c6e0173-faed-48b6-bded-369d9466e4f9)
The version are same as the repo leastest tag:
![image](https://github.com/user-attachments/assets/565c63e6-51b0-4803-8579-722ab55543e6)

Fellow your suggestions in response https://github.com/chaozwn/astronvim_with_coc_or_mason/issues/21#issuecomment-2208027823, I have also add the filetype of `neo-tree` in file of `~/.config/nvim/lua/plugins/barbecue.lua`：
```lua
return {
  "utilyre/barbecue.nvim",
  name = "barbecue",
  version = "*",
  dependencies = {
    "SmiteshP/nvim-navic",
    "nvim-tree/nvim-web-devicons", -- optional dependency
  },
  opts = {
    show_modified = true,
    exclude_filetypes = { "netrw", "toggleterm", "gomod", "gosum", "neo-tree" },
  },
}
```

**Comment by chaozwn** [comment]
> After update the barbecue plugin, the problem still appear. Now, after enter neovim then press Space + p + s to check the versions of barbecue plugin, there are: ![image](https://private-user-images.githubusercontent.com/49742133/350877430-8c6e0173-faed-48b6-bded-369d9466e4f9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MzQ2MzksIm5iZiI6MTcyMTYzNDMzOSwicGF0aCI6Ii80OTc0MjEzMy8zNTA4Nzc0MzAtOGM2ZTAxNzMtZmFlZC00OGI2LWJkZWQtMzY5ZDk0NjZlNGY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA3NDUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg4NmEyYTYyN2Y1ZTVkZDlmNGM1NTRmMzJmZWY2NDQxOTVmNzE3OTY1ZWU4YzM0ZWM2NGVlYThjY2NlNmQyNGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.c5J3VNvlDqux47l_K6VL6gwAoRWKykGBLzuWab6dvbg) The version are same as the repo leastest tag: ![image](https://private-user-images.githubusercontent.com/49742133/350877808-565c63e6-51b0-4803-8579-722ab55543e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MzQ2MzksIm5iZiI6MTcyMTYzNDMzOSwicGF0aCI6Ii80OTc0MjEzMy8zNTA4Nzc4MDgtNTY1YzYzZTYtNTFiMC00ODAzLTg1NzktNzIyYWI1NTU0M2U2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA3NDUzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTViODNlNjI4YWE2NTFlYzRlZTY0NWEzYjNlNTFjMjI0ZGI2MjZmNmQ0YTZmMjRmMzJjYThmZGRkOWMyZjQ2MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DCm2bd5SQyflYwgwm84WELWu4JWq-EVulxYheF9ywwM)
> 
> Fellow your suggestions in response [#21 (comment)](https://github.com/chaozwn/astronvim_with_coc_or_mason/issues/21#issuecomment-2208027823), I have also add the filetype of `neo-tree` in file of `~/.config/nvim/lua/plugins/barbecue.lua`：
> 
> ```lua
> return {
>   "utilyre/barbecue.nvim",
>   name = "barbecue",
>   version = "*",
>   dependencies = {
>     "SmiteshP/nvim-navic",
>     "nvim-tree/nvim-web-devicons", -- optional dependency
>   },
>   opts = {
>     show_modified = true,
>     exclude_filetypes = { "netrw", "toggleterm", "gomod", "gosum", "neo-tree" },
>   },
> }
> ```

in fact, this plugin is not stable enough at the moment, I have removed this plugin for now.

**Comment by Thesoul20** [comment]
So I should clone your repo again?

**Comment by chaozwn** [comment]
> So I should clone your repo again?

off course.

**Comment by Thesoul20** [comment]
After clone the least repo, there is no error when run command `nvim .`. Thanks a lot.
