### ISSUE TITLE
每次打开文件我都会提示 gopls 错误和 null-ls错误

### ISSUE THREAD

**Issue by skinhc** [chaozwn/astronvim_with_coc_or_mason#23]
![jietu](https://github.com/user-attachments/assets/4a77a2b7-41f7-4f99-8fbe-52f2250d971f)

**Comment by chaozwn** [comment]
This indicates that mason is installing the corresponding lsp and is waiting for the installation to complete.

**Comment by chaozwn** [comment]
Use the `<Leader>pm` to view the installation progress, `<Leader>` is `Space`

**Comment by skinhc** [comment]
> 这表示mason正在安装相应的lsp，等待安装完成。

我昨晚开了一晚上了,不是安装问题,是它已经安装失败了 我用命令行也装过了不行

**Comment by chaozwn** [comment]
> > 这表示mason正在安装相应的lsp，等待安装完成。
> 
> 我昨晚开了一晚上了,不是安装问题,是它已经安装失败了 我用命令行也装过了不行

because mason need to set up proxy, pls confirm your proxy is works normal?

**Comment by skinhc** [comment]
> > > 这表示mason正在安装相应的lsp，等待安装完成。
> > 
> > 
> > 我昨晚开了一晚上了,不是安装问题,是它已经安装失败了 我用命令行也装过了不行
> 
> because mason need to set up proxy, pls confirm your proxy is works normal?

gopls我在命令行已经安装过了,代理在命令行是正常的,使用 "nvim" 命令后不确定,在进入 nvim 后要重新设置代理吗?

**Comment by chaozwn** [comment]
> > > > 这表示mason正在安装相应的lsp，等待安装完成。
> > > 
> > > 
> > > 我昨晚开了一晚上了,不是安装问题,是它已经安装失败了 我用命令行也装过了不行
> > 
> > 
> > because mason need to set up proxy, pls confirm your proxy is works normal?
> 
> gopls我在命令行已经安装过了,代理在命令行是正常的,使用 "nvim" 命令后不确定,在进入 nvim 后要重新设置代理吗?

Can you watch my video on Bilibili, which tells how to set up a proxy?
