### ISSUE TITLE
Vue+Typescript+Vite项目中如果使用path alias，gf无法跳转到目标文件

### ISSUE THREAD

**Issue by tim-huang** [chaozwn/astronvim_with_coc_or_mason#24]
Vue 3.4.29 + typescript 5.4 + Vite 5.3.1

tsconfig.json配置
```json
{
    "paths": {
      "@/*": ["./src/*"]
    }
}
```

vite配置了
```typescript
export default defineConfig({
  plugins: [
    vue(),
    vueDevTools(),
  ],
  resolve: {
    alias: {
      '@': fileURLToPath(new URL('./src', import.meta.url))
    }
  }
})
```

在ts或vue文件中，使用`@`引用文件：
```typescript
import HelloWorld from '@/components/HelloWorld.vue'
```

此时在`HelloWorld`上使用`gd`可以跳转到正确的文件，但在`@/components/HelloWorld.vue`上使用`gf`无法跳转到文件。提示：
E447: 在路径中找不到文件 "/components/HelloWorld.vue"

**Comment by chaozwn** [comment]
> Vue 3.4.29 + typescript 5.4 + Vite 5.3.1
> 
> tsconfig.json配置
> 
> ```json
> {
>     "paths": {
>       "@/*": ["./src/*"]
>     }
> }
> ```
> 
> vite配置了
> 
> ```ts
> export default defineConfig({
>   plugins: [
>     vue(),
>     vueDevTools(),
>   ],
>   resolve: {
>     alias: {
>       '@': fileURLToPath(new URL('./src', import.meta.url))
>     }
>   }
> })
> ```
> 
> 在ts或vue文件中，使用`@`引用文件：
> 
> ```ts
> import HelloWorld from '@/components/HelloWorld.vue'
> ```
> 
> 此时在`HelloWorld`上使用`gd`可以跳转到正确的文件，但在`@/components/HelloWorld.vue`上使用`gf`无法跳转到文件。提示： E447: 在路径中找不到文件 "/components/HelloWorld.vue"

`gf` is function improved by `whick key`, which is support by lsp client. so you must use the real file path to use `gf`.

**Comment by tim-huang** [comment]
> > Vue 3.4.29 + typescript 5.4 + Vite 5.3.1
> > tsconfig.json配置
> > ```json
> > {
> >     "paths": {
> >       "@/*": ["./src/*"]
> >     }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > vite配置了
> > ```ts
> > export default defineConfig({
> >   plugins: [
> >     vue(),
> >     vueDevTools(),
> >   ],
> >   resolve: {
> >     alias: {
> >       '@': fileURLToPath(new URL('./src', import.meta.url))
> >     }
> >   }
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 在ts或vue文件中，使用`@`引用文件：
> > ```ts
> > import HelloWorld from '@/components/HelloWorld.vue'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 此时在`HelloWorld`上使用`gd`可以跳转到正确的文件，但在`@/components/HelloWorld.vue`上使用`gf`无法跳转到文件。提示： E447: 在路径中找不到文件 "/components/HelloWorld.vue"
> 
> `gf` is function improved by `whick key`, which is support by lsp client. so you must use the real file path to use `gf`.

Thanks for your quick response, I got it.
