### ISSUE TITLE
cannot commet by Leader + /

### ISSUE THREAD

**Issue by Thesoul20** [chaozwn/astronvim_with_coc_or_mason#26]
The settings in the file of `comment.lua` do not change any all:
```lua
  {
    "AstroNvim/astrocore",
    ---@param opts AstroCoreOpts
    opts = function(_, opts)
      local maps = require("astrocore").empty_map_table()
      maps.n["<C-/>"] = opts.mappings.n["<Leader>/"]
      maps.x["<C-/>"] = opts.mappings.x["<Leader>/"]
      maps.n["<Leader>/"] = false
      maps.x["<Leader>/"] = false

      opts.mappings = require("astrocore").extend_tbl(opts.mappings, maps)
    end,
  },
```

But when using <Leader>(space) + / in neovim, there is no comment but search:
![image](https://github.com/user-attachments/assets/50963c08-429e-4382-a512-9a25f9f77c82)

So how to quickly comment by <Leader> + / ?

**Comment by chaozwn** [comment]
> The settings in the file of `comment.lua` do not change any all:
> 
> ```lua
>   {
>     "AstroNvim/astrocore",
>     ---@param opts AstroCoreOpts
>     opts = function(_, opts)
>       local maps = require("astrocore").empty_map_table()
>       maps.n["<C-/>"] = opts.mappings.n["<Leader>/"]
>       maps.x["<C-/>"] = opts.mappings.x["<Leader>/"]
>       maps.n["<Leader>/"] = false
>       maps.x["<Leader>/"] = false
> 
>       opts.mappings = require("astrocore").extend_tbl(opts.mappings, maps)
>     end,
>   },
> ```
> 
> But when using (space) + / in neovim, there is no comment but search: ![image](https://private-user-images.githubusercontent.com/49742133/356795876-50963c08-429e-4382-a512-9a25f9f77c82.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzNDg5NTAsIm5iZiI6MTcyMzM0ODY1MCwicGF0aCI6Ii80OTc0MjEzMy8zNTY3OTU4NzYtNTA5NjNjMDgtNDI5ZS00MzgyLWE1MTItOWEyNWY5Zjc3YzgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODExVDAzNTczMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMxODI4NDE3NGMyNjkwMzJhYjhlZjE3YjY2ZGMxYzRkMDY3ZDFhYjk0NWY1OGMyMjQ5YTBlZjE1MzI1ZDE3ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6iCHkL3ZOH46QcWIY3fh2OBmfqjh3e7JO4oyYe1sFaE)
> 
> So how to quickly comment by + / ?

because i don't like use `space + /` to comment code, so i use `<C-/>` as replace. you can delete 7, 8 lines in above image.

**Comment by Thesoul20** [comment]
> because i don't like use `space + /` to comment code, so i use `<C-/>` as replace. you can delete 7, 8 lines in above image.

Thanks a lot. I have changed the as follow:
```lua
  {
    "AstroNvim/astrocore",
    ---@param opts AstroCoreOpts
    opts = function(_, opts)
      local maps = require("astrocore").empty_map_table()
      maps.n["<C-/>"] = opts.mappings.n["<Leader>/"]
      maps.x["<C-/>"] = opts.mappings.x["<Leader>/"]

      opts.mappings = require("astrocore").extend_tbl(opts.mappings, maps)
    end,
  },
```
By the way, in the readme.md file, there are:
> Create a new user repository from this template
Press the "Use this template" button above to create a new repository to store your user configuration.

But I do not found the button `"Use this template"` any more, So how do I generated my own neovim config?

**Comment by chaozwn** [comment]
> > because i don't like use `space + /` to comment code, so i use `<C-/>` as replace. you can delete 7, 8 lines in above image.
> 
> Thanks a lot. I have changed the as follow:
> 
> ```lua
>   {
>     "AstroNvim/astrocore",
>     ---@param opts AstroCoreOpts
>     opts = function(_, opts)
>       local maps = require("astrocore").empty_map_table()
>       maps.n["<C-/>"] = opts.mappings.n["<Leader>/"]
>       maps.x["<C-/>"] = opts.mappings.x["<Leader>/"]
> 
>       opts.mappings = require("astrocore").extend_tbl(opts.mappings, maps)
>     end,
>   },
> ```
> 
> By the way, in the readme.md file, there are:
> 
> > Create a new user repository from this template
> > Press the "Use this template" button above to create a new repository to store your user configuration.
> 
> But I do not found the button `"Use this template"` any more, So how do I generated my own neovim config?

Instead of using my template, you can only use astronvim's template and write the configuration from 0.
