### ISSUE TITLE
有使用linux的安装脚本吗，我看安装命令step.sh里面的内容是macOS的

### ISSUE THREAD

**Issue by tp-life** [chaozwn/astronvim_with_coc_or_mason#27]
如题

**Comment by chaozwn** [comment]
> 如题

理论上你直接把brew install 换成apt install就可以了，大部分组件linux和mac是通用的。

**Comment by tp-life** [comment]
尝试过一下，发现里面很多工具其实并不是跨平台的，很多工具都不存在

**Comment by chaozwn** [comment]
> 尝试过一下，发现里面很多工具其实并不是跨平台的，很多工具都不存在

linux也有brew的. https://docs.brew.sh/Homebrew-on-Linux
