### ISSUE TITLE
How to insert a tab using <Tab> 

### ISSUE THREAD

**Issue by muzhancun** [chaozwn/astronvim_with_coc_or_mason#3]
lsp type is "lsp"

**Comment by chaozwn** [comment]
> lsp type is "lsp"

<C-e> cancel cmp window. then input <Tab>.

**Comment by muzhancun** [comment]
https://github.com/chaozwn/astronvim_with_coc_or_mason/assets/91790440/e67f31d8-8b70-495e-b5c4-39a8bf6df015

tab for cmp is good, can't insert a tab when cmp window closed though

**Comment by chaozwn** [comment]
> 2023-07-04.11.00.45.mov 
> tab for cmp is good, can't insert a tab when cmp window closed though
I don't quite understand your requirement. Do you want to output a tab when pressing "<TAB>", or do you want to output a space when pressing "tab"?

**Comment by muzhancun** [comment]
> 

I want to output a "tab" i.e. four spaces using <TAB> key when there is nothing to be completed.

**Comment by chaozwn** [comment]
> > 
> 
> I want to output a "tab" i.e. four spaces using key when there is nothing to be completed.

i works well. can not reproduce.

https://github.com/chaozwn/astronvim_with_coc_or_mason/assets/51357674/abbe0792-69d7-421f-9060-6197370eb75a

**Comment by muzhancun** [comment]
well

**Comment by muzhancun** [comment]
> > > 
> > 
> > 
> > I want to output a "tab" i.e. four spaces using key when there is nothing to be completed.
> 
> i works well. can not reproduce.
> 
>  Screen.Recording.2023-07-04.at.12.59.57.mov

Fixed by this discussion, https://github.com/zbirenbaum/copilot.lua/discussions/153. It's a problem caused by copilot.lua
