### ISSUE TITLE
Docker版本的nvim ide

### ISSUE THREAD

**Issue by DangGwanHou** [chaozwn/astronvim_with_coc_or_mason#30]
作者您好，从B站上看到了您的nvim教程后非常喜欢，无奈网络环境太差，使用mason安装插件时总会冒出一两个报错，请问作者可以帮忙做成一个docker镜像以便随拉随用吗

**Comment by DangGwanHou** [comment]
已经做出来了，8个G太大了....😅

**Comment by chaozwn** [comment]
> 已经做出来了，8个G太大了....😅

这个应该是你的基础镜像的原因把。。

**Comment by DangGwanHou** [comment]
> > 已经做出来了，8个G太大了....😅
> 
> 这个应该是你的基础镜像的原因把。。

可能是，不纠结了。
另外请问作者是否有空可以帮忙支持一下这个主题`xiantang/darcula-dark.nvim`。感激不尽

**Comment by chaozwn** [comment]
> > > 已经做出来了，8个G太大了....😅
> > 
> > 
> > 这个应该是你的基础镜像的原因把。。
> 
> 可能是，不纠结了。 另外请问作者是否有空可以帮忙支持一下这个主题`xiantang/darcula-dark.nvim`。感激不尽

可以

**Comment by chaozwn** [comment]
> > > 已经做出来了，8个G太大了....😅
> > 
> > 
> > 这个应该是你的基础镜像的原因把。。
> 
> 可能是，不纠结了。 另外请问作者是否有空可以帮忙支持一下这个主题`xiantang/darcula-dark.nvim`。感激不尽

你自己改下astro-ui里面是colorscheme就好，我已经默认包含这个主题了，你可以用`<Leader>fT`查看我默认支持的所有主题
<img width="1440" alt="image" src="https://github.com/user-attachments/assets/48e2e71d-732a-4b04-9848-7f76e12c5bda" />
