### ISSUE TITLE
key remap not working???

### ISSUE THREAD

**Issue by RayneScofield** [chaozwn/astronvim_with_coc_or_mason#32]
```
maps.n["<C-/>"] = opts.mappings.n["<Leader>/"]
maps.x["<C-/>"] = opts.mappings.x["<Leader>/"]

```

 ```
maps.n["<Leader>bo"] = maps.n["<Leader>bc"]
```

press `<C-/>` not working to comment line and `<leader>bc` not working to close buffers as well

Does it working for you guys?

**Comment by chaozwn** [comment]
`<C-/>` not work maybe cause your terminal or `tmux`, do you use `tmux`?

**Comment by chaozwn** [comment]
`maps.n["<Leader>bc"]`, i use `bufferline.nvim` and never set `maps.n["<Leader>bc"]` mapping, so it not works.

**Comment by RayneScofield** [comment]
> `<C-/>` not work maybe cause your terminal or `tmux`, do you use `tmux`?

It's just not working no matter it is in tmux or not.  maybe it is my terminal issue.

may be map ` maps.n["<C-/>"] = ` to an actual command is a better solution.

**Comment by chaozwn** [comment]
> > `<C-/>` not work maybe cause your terminal or `tmux`, do you use `tmux`?
> 
> It's just not working no matter it is in tmux or not. maybe it is my terminal issue.
> 
> may be map `maps.n["<C-/>"] =` to an actual command is a better solution.

sure, You can modify the `comment.lua` file directly.

<img width="1321" alt="image" src="https://github.com/user-attachments/assets/39cb0a9b-e4d7-4a3e-9199-f246bbb1a78f" />
