### ISSUE TITLE
nvim打开dap错误

### ISSUE THREAD

**Issue by acwwt** [chaozwn/astronvim_with_coc_or_mason#4]
我的nvim打开的时候会显示这个错误, 我觉得他是少了dap, 但是我又不知道怎么去安装他.
![Snipaste_2023-07-16_14-49-08](https://github.com/chaozwn/astronvim_with_coc_or_mason/assets/110531742/c7eb093d-1477-4885-8c4e-fb68d78fcdc1)

**Comment by chaozwn** [comment]
> 我的nvim打开的时候会显示这个错误, 我觉得他是少了dap, 但是我又不知道怎么去安装他. ![Snipaste_2023-07-16_14-49-08](https://user-images.githubusercontent.com/110531742/253793370-c7eb093d-1477-4885-8c4e-fb68d78fcdc1.png)

这个是用的我的配置吗？

**Comment by chaozwn** [comment]
![image](https://github.com/chaozwn/astronvim_with_coc_or_mason/assets/51357674/6aaf93f7-3b83-4310-b5a5-a5d93d0cebc0)
dap默认是不支持win系统的，如果你要使用完整的dap功能，必须使用wsl2.

**Comment by acwwt** [comment]
windows要怎么配置啊

**Comment by chaozwn** [comment]
> windows要怎么配置啊

搜索下windows中wsl2使用unbutu

**Comment by acwwt** [comment]
ubuntu里面的astronvim是不是没有lazygit啊?

sudo apt-get install lazygit

**Comment by Love-laughing-bear-is-bear-two** [comment]
![image](https://github.com/chaozwn/astronvim_with_coc_or_mason/assets/110531742/a6ebdfcf-7cd6-4319-973f-12493827f344)

**Comment by acwwt** [comment]
![image](https://github.com/chaozwn/astronvim_with_coc_or_mason/assets/110531742/9e3938e2-2b48-49ed-8a9e-fcf48896188f)
我这个插件在init里面用不用导入

**Comment by Hujiazeng** [comment]
同样的问题

**Comment by Hujiazeng** [comment]
只想用windows

**Comment by chaozwn** [comment]
> 只想用windows

那只能用wsl2，在linux里面跑neovim

**Comment by Hujiazeng** [comment]
b站视频我基本都看完了, 讲的很好。关于debug有其他替代的方案吗

**Comment by chaozwn** [comment]
> b站视频我基本都看完了, 讲的很好。关于debug有其他替代的方案吗

目前没有, 我现在用的astronvim v4, 视频都是v3的。其实我建议你装下wsl2，毕竟docker这些都依赖linux。目前主分支，支持go,rust,react,markdown开发。
