### ISSUE TITLE
alpha.lua头部不生效

### ISSUE THREAD

**Issue by acwwt** [chaozwn/astronvim_with_coc_or_mason#5]
![image](https://github.com/chaozwn/astronvim_with_coc_or_mason/assets/110531742/35e59f0a-480a-4443-a1d3-8283865ad091)
![image](https://github.com/chaozwn/astronvim_with_coc_or_mason/assets/110531742/fdfb2ee1-ed62-49d1-a0a6-48d9611ed8f2)
头部不生效但是button生效

**Comment by chaozwn** [comment]
> 
用方括号表示字符串

**Comment by acwwt** [comment]
还是不行

**Comment by chaozwn** [comment]
I don't use `alpha.lua` in my configuration
