### ISSUE TITLE
如何将 `jk` 设置为 Esc键以退出输入模式

### ISSUE THREAD

**Issue by Thesoul20** [chaozwn/astronvim_with_coc_or_mason#6]
您好，我在`nvim/lua/user/keymaps.lua`中设置了以下的设置：
`  maps.i["jk"] = {"ESC"}` 

但是并没有作用，只是能够在输入`jk` 时出现 ESC 字样，完成了一个字符上的替换，而并没有退出输入模式。

需要怎样的设置才能够将`jk`设置为ESC 键呢？

**Comment by chaozwn** [comment]
> 

![image](https://github.com/chaozwn/astronvim_with_coc_or_mason/assets/51357674/236dde04-d529-42ae-92b2-4b6e2b025272)

**Comment by Thesoul20** [comment]
仔细看了一下别人的设置，发现这样的设置就可以实现：
`  maps.i["jk"] = {"<ESC>"}`

`<key>` 应该是代表着一个键位。
