### ISSUE TITLE
打开一个悬浮终端后，如何隐藏该终端

### ISSUE THREAD

**Issue by Thesoul20** [chaozwn/astronvim_with_coc_or_mason#7]
使用`<leader>tf` 可以新建一个终端，在进行一系列的操作后，如何通过键位回到Nvim 编辑器中，并保持终端会话。（虽然使用鼠标会达到这种效果，但鼠标的效率太低）

**Comment by chaozwn** [comment]
<C-'> <C-h><C-j><C-k><C-l>都可以，lazygit和joshuto只能通过q退出

**Comment by chaozwn** [comment]
> 使用`<leader>tf` 可以新建一个终端，在进行一系列的操作后，如何通过键位回到Nvim 编辑器中，并保持终端会话。（虽然使用鼠标会达到这种效果，但鼠标的效率太低）

<C-'><C-h,j,k,l> 都可以，lazygit和joshuto只能通过q退出
