### ISSUE TITLE
不能够正常打开ipython 窗口

### ISSUE THREAD

**Issue by Thesoul20** [chaozwn/astronvim_with_coc_or_mason#8]
在设置完当前Python的路径后， 并不能够正常的打开ipython 窗口以运行jypyter notebook file.
local neoconf.json (use virtual environment created by pipenv):
```json
{
"lspconfig": {
    "pyright": {
      "python.pythonPath": "~/envs/pytorch/.venv/bin/python"
    }

  }
}
```
pyright parameters which showed by `leader + p + b`:
![parameters in pyright](https://github.com/chaozwn/astronvim_with_coc_or_mason/assets/49742133/1a8e086d-7781-4d83-ad6a-27196e904c60)

the output of command `leader + j + o+ o`:
![the open windows by jupyter](https://github.com/chaozwn/astronvim_with_coc_or_mason/assets/49742133/e07f18be-9b9a-4b41-a49c-118667a3fdd6)

所以我应该怎样使用Jupyer 插件呢？

**Comment by chaozwn** [comment]
> 

![image](https://github.com/chaozwn/astronvim_with_coc_or_mason/assets/51357674/b014fdcf-8b8f-4a03-9039-1065e382ced6)

**Comment by Thesoul20** [comment]
直接将`jupyter.lua`文件中的`vim.g.jukit_shell_cmd`注释掉就能够正常使用了。
